// client/src/components/Projects/Portfolio.vue
<template>
  <v-container fluid grid-list-xl>

    <!-- Page Title -->
    <v-layout text-xs-center row wrap>
      <v-flex xs12 sm6 offset-sm3>
        <h1 class="main-title">My Portfolio</h1>
      </v-flex>
    </v-layout>

    <!-- Project Card -->
    <v-layout row wrap v-if="infiniteScrollProjects">
      <v-flex xs12 sm6 v-for="project in infiniteScrollProjects.projects" :key="project._id">
        <v-card hover>

          <v-img @click.native="goToProject(project._id)" :src="project.imageUrl" lazy height="30vh"></v-img>

          <v-card-actions>
            <v-card-title primary>
              <div>
                <div class="headline">{{project.title}}</div>
              </div>
            </v-card-title>
            <v-spacer></v-spacer>
            <v-btn icon @click="showProjectDetails = !showProjectDetails">
              <v-icon>{{`keyboard_arrow_${showProjectDetails ? 'up' : 'down'}`}}</v-icon>
            </v-btn>
          </v-card-actions>

          <v-slide-y-transition>
            <v-card-text v-show="showProjectDetails" color="grey lighten-4">
              <v-list-tile>
                <v-list-tile-content>
                  <v-list-tile-title class="text--primary">
                    {{formatDescription(project.description)}}
                  </v-list-tile-title>
                  <v-list-tile-subtitle class="font-weight-thin">
                    Added {{project.dateAdded}}
                  </v-list-tile-subtitle>
                </v-list-tile-content>

                <v-list-tile-action >
                  <v-btn @click="goToProject(project._id)" ripple icon>
                    <v-icon color="grey lighten-1">info</v-icon>
                  </v-btn>
                </v-list-tile-action>

              </v-list-tile>
            </v-card-text>
          </v-slide-y-transition>

        </v-card>
      </v-flex>
    </v-layout>

    <!-- fetch more button -->
    <v-layout column v-if="showMoreEnabled">
      <v-flex xs12>
        <v-layout justify-center row>
          <v-btn color="info" @click="showMore">Show More</v-btn>
        </v-layout>
      </v-flex>
    </v-layout>

  </v-container>
</template>

<script>
import { INFINITE_SCROLL_PROJECTS } from '../../queries';
const pageSize = 4;
export default {
  name: 'Projects',
  data(){
    return {
      showMoreEnabled: true,
      pageNum: 1,
      showProjectDetails: false
    }
  },
  apollo: {
    infiniteScrollProjects: {
      query: INFINITE_SCROLL_PROJECTS,
      variables: {
        pageSize,
        pageNum: 1
      }
    }
  },
  methods: {
    goToProject(projectId){
      this.$router.push(`/projects/${projectId}`);
    },
    formatDescription(desc){
      return desc.length > 25 ? `${desc.slice(0, 25)}...` : desc;
    },
    showMore(){
      this.pageNum += 1;
      this.$apollo.queries.infiniteScrollProjects.fetchMore({
        variables: {
          pageSize,
          pageNum: this.pageNum
        },
        //combine the new results with the old
        updateQuery: (prevResult, {fetchMoreResult}) => {
          const newProjects = fetchMoreResult.infiniteScrollProjects.projects;
          const hasMore = fetchMoreResult.infiniteScrollProjects.hasMore;
          this.showMoreEnabled = hasMore;

          return {
            infiniteScrollProjects: {
              __typename: prevResult.infiniteScrollProjects.__typename,
              hasMore,
              projects: [
                ...prevResult.infiniteScrollProjects.projects,
                ...newProjects
              ]
            }
          };
        }
      });
    },
  }
}
</script>

// react-refactor/client/src/components/Portfolio/index.js
import React, { useState } from 'react';
import withStyles from '@material-ui/core/styles/withStyles';
import { Query } from 'react-apollo';
import Button from '@material-ui/core/Button';
import Grid from '@material-ui/core/Grid';

import ProjectCard from './ProjectCard';
import Loading from '../Shared/Loading';
import Error from '../Shared/Error';
import { INFINITE_SCROLL_PROJECTS_QUERY } from '../../graphql';

const Portfolio = ({ classes, history }) => {
  const pageSize = 4;
  let pageNum = 1;

  const routeToProject = projectId => {
    history.push(`/project/${projectId}`);
  };

  const handleShowMore = fetch => {
    pageNum += 1;
    fetch({
      variables: {
        pageSize,
        pageNum
      },
      // combine new results with the old results
      updateQuery: (prevResult, { fetchMoreResult }) => {
        const newProjects = fetchMoreResult.infiniteScrollProjects.projects;
        const hasMore = fetchMoreResult.infiniteScrollProjects.hasMore;
        return {
          infiniteScrollProjects: {
            __typename: prevResult.infiniteScrollProjects.__typename,
            hasMore,
            projects: [
              ...prevResult.infiniteScrollProjects.projects,
              ...newProjects
            ]
          }
        };
      }
    });
  };

  return (
    <Query
      query={INFINITE_SCROLL_PROJECTS_QUERY}
      variables={{ pageSize, pageNum }}
    >
      {({ data, loading, error, fetchMore }) => {
        if (loading) return <Loading />;
        if (error) return <Error error={error} />;

        return (
          <>
            <Grid container direction='row' xs={12} sm={6} spacing={40}>
              {/* Project Cards */}
              {data.infiniteScrollProjects.projects.map(project => (
                <ProjectCard
                  key={project._id}
                  project={project}
                  routeToProject={() => routeToProject(project._id)}
                />
              ))}
            </Grid>

            {/* Fetch More Button */}
            {data.infiniteScrollProjects.projects.length &&
              data.infiniteScrollProjects.hasMore && (
                <Button
                  onClick={() => handleShowMore(fetchMore)}
                  color='secondary'
                  disabled={loading}
                  size='medium'
                >
                  Show More
                </Button>
              )}
          </>
        );
      }}
    </Query>
  );
};

const styles = theme => ({
  root: {}
});

export default withStyles(styles)(Portfolio);
